import {
  dataSourceReferenceSchema,
  type DataSourceReference,
} from "@/lib/data/schemas/source";

const ACCESSED_AT = "2026-07-17";

const rawSources = [
  {
    id: "jpl-planetary-physical-parameters",
    provider: "NASA Jet Propulsion Laboratory",
    title: "Planetary Physical Parameters",
    url: "https://ssd.jpl.nasa.gov/planets/phys_par.html",
    sourceType: "dataset",
    freshness: "reference",
    accessedAt: ACCESSED_AT,
    publishedOrUpdatedAt: "2019-12-12",
    notes: {
      en: "Primary reference for radii, mass, density, rotation, orbital period, gravity and escape velocity.",
      tr: "Yarıçap, kütle, yoğunluk, dönüş, yörünge süresi, yerçekimi ve kaçış hızı için birincil referans.",
    },
  },
  {
    id: "jpl-approximate-planetary-elements",
    provider: "NASA Jet Propulsion Laboratory",
    title: "Approximate Positions of the Planets",
    url: "https://ssd.jpl.nasa.gov/planets/approx_pos.html",
    sourceType: "dataset",
    freshness: "reference",
    accessedAt: ACCESSED_AT,
    notes: {
      en: "J2000-fit semimajor axis, eccentricity and inclination used for explanatory orbit geometry, not precise ephemerides.",
      tr: "Açıklayıcı yörünge geometrisi için kullanılan J2000 uyumlu büyük yarı eksen, dışmerkezlik ve eğim değerleri; kesin efemeris değildir.",
    },
  },
  {
    id: "jpl-planetary-satellite-mean-elements",
    provider: "NASA Jet Propulsion Laboratory",
    title: "Planetary Satellite Mean Elements",
    url: "https://ssd.jpl.nasa.gov/sats/elem/",
    sourceType: "dataset",
    freshness: "reference",
    accessedAt: "2026-07-19",
    notes: {
      en: "Published mean orbital elements and epochs used for deterministic featured-moon previews. JPL distinguishes these tables from precision ephemerides.",
      tr: "Deterministik öne çıkan uydu önizlemelerinde kullanılan yayımlanmış ortalama yörünge elemanları ve epoch kayıtları. JPL bu tabloları kesin efemeristen ayırır.",
    },
  },
  {
    id: "jpl-planetary-satellite-physical-parameters",
    provider: "NASA Jet Propulsion Laboratory",
    title: "Planetary Satellite Physical Parameters",
    url: "https://ssd.jpl.nasa.gov/sats/phys_par/",
    sourceType: "dataset",
    freshness: "reference",
    accessedAt: "2026-07-19",
    notes: {
      en: "Mean radii used by the featured major moon catalogue and its physical-to-visual scale separation.",
      tr: "Öne çıkan büyük uydu kataloğunda ve fiziksel/görsel ölçek ayrımında kullanılan ortalama yarıçaplar.",
    },
  },
  {
    id: "jpl-sbdb-orbital-elements",
    provider: "NASA Jet Propulsion Laboratory",
    title: "Small-Body Database API and Element Tables",
    url: "https://ssd-api.jpl.nasa.gov/doc/sbdb.html",
    sourceType: "dataset",
    freshness: "latest-available",
    accessedAt: "2026-07-19",
    notes: {
      en: "TDB epoch and J2000 heliocentric-ecliptic osculating elements used only for labelled representative two-body previews.",
      tr: "Yalnızca etiketli iki-cisim temsili önizlemelerde kullanılan TDB epoch ve J2000 Güneş merkezli ekliptik osculating elemanları.",
    },
  },
  {
    id: "jpl-horizons-api",
    provider: "NASA Jet Propulsion Laboratory",
    title: "Horizons API",
    url: "https://ssd-api.jpl.nasa.gov/doc/horizons.html",
    sourceType: "api",
    freshness: "latest-available",
    accessedAt: "2026-07-19",
    notes: {
      en: "Navigation-grade state-vector source for bounded accurate windows; output frame, reference plane, correction and TDB settings are explicit.",
      tr: "Sınırlı doğru pencereler için navigasyon düzeyinde durum vektörü kaynağı; çıktı frame, referans düzlemi, düzeltme ve TDB ayarları açıktır.",
    },
  },
  {
    id: "naif-spice-frames",
    provider: "NASA Navigation and Ancillary Information Facility",
    title: "SPICE Reference Frames Required Reading",
    url: "https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/FORTRAN/req/frames.html",
    sourceType: "article",
    freshness: "reference",
    accessedAt: "2026-07-19",
    notes: {
      en: "Primary frame terminology and inertial/body-fixed transformation contract.",
      tr: "Birincil frame terminolojisi ile atalet/body-fixed dönüşüm sözleşmesi.",
    },
  },
  {
    id: "naif-spice-pck",
    provider: "NASA Navigation and Ancillary Information Facility",
    title: "SPICE PCK Required Reading",
    url: "https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/MATLAB/req/pck.html",
    sourceType: "article",
    freshness: "reference",
    accessedAt: "2026-07-19",
    notes: {
      en: "Primary body-orientation and pole-model terminology used to keep parent equatorial and body-fixed claims separate.",
      tr: "Parent equatorial ve body-fixed iddialarını ayırmak için kullanılan birincil gövde yönelim ve kutup modeli terminolojisi.",
    },
  },
  {
    id: "iau-rotational-elements-2015",
    provider:
      "IAU Working Group on Cartographic Coordinates and Rotational Elements",
    title:
      "Report of the IAU Working Group on Cartographic Coordinates and Rotational Elements: 2015",
    url: "https://doi.org/10.1007/s10569-017-9805-5",
    sourceType: "article",
    freshness: "reference",
    accessedAt: "2026-07-19",
    notes: {
      en: "Pole and rotational-element authority; texture prime-meridian alignment remains explicitly unverified until Prompt 3 assets are sourced.",
      tr: "Kutup ve dönüş elemanları otoritesi; texture başlangıç meridyeni hizası Prompt 3 varlıkları kaynaklandırılana kadar açıkça doğrulanmamıştır.",
    },
  },
  {
    id: "nasa-planet-order-distance",
    provider: "NASA Science",
    title: "Planet Sizes and Locations in Our Solar System",
    url: "https://science.nasa.gov/solar-system/planet-sizes-and-locations-in-our-solar-system/",
    sourceType: "article",
    freshness: "reference",
    accessedAt: ACCESSED_AT,
  },
  {
    id: "nasa-sun-fact-sheet",
    provider: "NASA Goddard Space Flight Center",
    title: "Sun Fact Sheet",
    url: "https://nssdc.gsfc.nasa.gov/planetary/factsheet/sunfact.html",
    sourceType: "dataset",
    freshness: "reference",
    accessedAt: ACCESSED_AT,
    publishedOrUpdatedAt: "2024-05-09",
    notes: {
      en: "Volumetric mean radius used by the sourced Sun scene model.",
      tr: "Kaynaklı Güneş sahne modelinde kullanılan hacimsel ortalama yarıçap.",
    },
  },
  {
    id: "nasa-solar-system-temperatures",
    provider: "NASA Science",
    title: "Temperatures Across Our Solar System",
    url: "https://science.nasa.gov/solar-system/temperatures-across-our-solar-system/",
    sourceType: "article",
    freshness: "reference",
    accessedAt: ACCESSED_AT,
    publishedOrUpdatedAt: "2025-04-29",
    notes: {
      en: "Rocky-planet values are surface means; giant-planet values use an Earth sea-level-equivalent pressure layer.",
      tr: "Kayalık gezegen değerleri yüzey ortalamasıdır; dev gezegenlerde Dünya deniz seviyesi basıncına eşdeğer atmosfer katmanı kullanılır.",
    },
  },
  ...planetFactSources(),
  {
    id: "nasa-earth-moon-facts",
    provider: "NASA Science",
    title: "Moon Facts",
    url: "https://science.nasa.gov/moon/facts/",
    sourceType: "article",
    freshness: "reference",
    accessedAt: ACCESSED_AT,
    publishedOrUpdatedAt: "2026-02-12",
  },
  {
    id: "nasa-mars-moons-facts",
    provider: "NASA Science",
    title: "Mars Moons: Facts",
    url: "https://science.nasa.gov/mars/moons/facts/",
    sourceType: "article",
    freshness: "reference",
    accessedAt: ACCESSED_AT,
    publishedOrUpdatedAt: "2024-11-03",
  },
  {
    id: "nasa-messenger-mission",
    provider: "NASA Science",
    title: "MESSENGER",
    url: "https://science.nasa.gov/mission/messenger/",
    sourceType: "mission",
    freshness: "historical",
    accessedAt: "2026-07-18",
    notes: {
      en: "Official mission record for the first spacecraft to orbit Mercury.",
      tr: "Merkür yörüngesine giren ilk uzay aracı için resmî görev kaydı.",
    },
  },
  {
    id: "nasa-magellan-mission",
    provider: "NASA Science",
    title: "Magellan",
    url: "https://science.nasa.gov/mission/magellan/",
    sourceType: "mission",
    freshness: "historical",
    accessedAt: "2026-07-18",
  },
  {
    id: "nasa-davinci-mission",
    provider: "NASA Science",
    title: "DAVINCI",
    url: "https://science.nasa.gov/mission/davinci/",
    sourceType: "mission",
    freshness: "latest-available",
    accessedAt: "2026-07-18",
    publishedOrUpdatedAt: "2026-07-14",
    notes: {
      en: "Future Venus flyby and atmospheric-probe mission; schedules can change.",
      tr: "Gelecekteki Venüs geçişi ve atmosfer sondası görevi; takvim değişebilir.",
    },
  },
  {
    id: "nasa-terra-mission",
    provider: "NASA Science",
    title: "Terra",
    url: "https://science.nasa.gov/mission/terra/",
    sourceType: "mission",
    freshness: "latest-available",
    accessedAt: "2026-07-18",
    publishedOrUpdatedAt: "2025-11-28",
  },
  {
    id: "nasa-perseverance-mission",
    provider: "NASA Science",
    title: "Mars 2020: Perseverance Rover",
    url: "https://science.nasa.gov/mission/mars-2020-perseverance/",
    sourceType: "mission",
    freshness: "latest-available",
    accessedAt: "2026-07-18",
    notes: {
      en: "Mission overview used for goals and scope, not as a whole-planet live-data source.",
      tr: "Görev hedefleri ve kapsamı için kullanılır; tüm gezegenin canlı veri kaynağı değildir.",
    },
  },
  {
    id: "nasa-juno-mission",
    provider: "NASA Science",
    title: "Juno",
    url: "https://science.nasa.gov/mission/juno/",
    sourceType: "mission",
    freshness: "latest-available",
    accessedAt: "2026-07-18",
  },
  {
    id: "nasa-cassini-mission",
    provider: "NASA Science",
    title: "Cassini-Huygens",
    url: "https://science.nasa.gov/mission/Cassini/",
    sourceType: "mission",
    freshness: "historical",
    accessedAt: "2026-07-18",
  },
  {
    id: "nasa-voyager-2-mission",
    provider: "NASA Science",
    title: "Voyager 2",
    url: "https://science.nasa.gov/mission/voyager/voyager-2/",
    sourceType: "mission",
    freshness: "historical",
    accessedAt: "2026-07-18",
    notes: {
      en: "Official record for the only spacecraft flybys of Uranus and Neptune.",
      tr: "Uranüs ve Neptün'e yapılan tek uzay aracı yakın geçişlerinin resmî kaydı.",
    },
  },
  {
    id: "jpl-planetary-satellite-discoveries",
    provider: "NASA Jet Propulsion Laboratory",
    title: "Planetary Satellite Discovery Circumstances",
    url: "https://ssd.jpl.nasa.gov/sats/discovery.html",
    sourceType: "dataset",
    freshness: "latest-available",
    accessedAt: ACCESSED_AT,
    notes: {
      en: "IAU-recognized planetary satellite list used for the dated moon-count snapshot.",
      tr: "Tarihli uydu sayısı kaydı için kullanılan, IAU tarafından tanınan gezegen uyduları listesi.",
    },
  },
] as const;

function planetFactSources() {
  const facts = [
    ["mercury", "Mercury: Facts", "https://science.nasa.gov/mercury/facts/"],
    ["venus", "Venus: Facts", "https://science.nasa.gov/venus/venus-facts/"],
    ["earth", "Facts About Earth", "https://science.nasa.gov/earth/facts/"],
    ["mars", "Mars: Facts", "https://science.nasa.gov/mars/facts/"],
    [
      "jupiter",
      "Jupiter Facts",
      "https://science.nasa.gov/jupiter/jupiter-facts/",
    ],
    ["saturn", "Saturn: Facts", "https://science.nasa.gov/saturn/facts/"],
    ["uranus", "Uranus: Facts", "https://science.nasa.gov/uranus/facts/"],
    [
      "neptune",
      "Neptune: Facts",
      "https://science.nasa.gov/neptune/neptune-facts/",
    ],
  ] as const;

  return facts.map(([id, title, url]) => ({
    id: `nasa-${id}-facts`,
    provider: "NASA Science",
    title,
    url,
    sourceType: "article" as const,
    freshness: "reference" as const,
    accessedAt: ACCESSED_AT,
  }));
}

export const planetaryReferenceSources: readonly DataSourceReference[] =
  Object.freeze(
    rawSources.map((source) => dataSourceReferenceSchema.parse(source)),
  );

export const planetaryReferenceSourceById = new Map(
  planetaryReferenceSources.map((source) => [source.id, source] as const),
);
