name: Vercel lint

on:
  repository_dispatch:
    types: [vercel.deployment.ready]

permissions:
  actions: read
  contents: read
  statuses: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out deployment source
        uses: vercel/repository-dispatch/actions/checkout@v1
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: notify vercel
        uses: vercel/repository-dispatch/actions/status@v1
        with:
          name: "Vercel - helios: lint"
      - run: pnpm lint
